apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ibuildthecloud/istio-gh.git'
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
      chart: istio
      repoURL: https://istio-release.storage.googleapis.com/charts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
