global:
  istioNamespace: istio-system
  proxy:
    autoInject: enabled
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true

pilot:
  enabled: true

ingressGateways:
  - name: istio-ingressgateway
    enabled: true

egressGateways:
  - name: istio-egressgateway
    enabled: true

sidecarInjectorWebhook:
  enabled: true
